### ISSUE TITLE
PutShipCommand boundary check bug

### ISSUE THREAD

**Issue by erjillsison** [CS2103-AY1819S2-W14-3/main#105]
isBodyWithinBounds() method in PutShipCommand does not work properly.
![image](https://user-images.githubusercontent.com/22665593/54079979-b4ee2b00-4321-11e9-8186-81b5987bcd18.png)

Line 123 and 124 should have > inequality instead of >=.
Also, because of the || on line 124, it ignores orientation which should not be the case. 
e.g Put a length 2 ship horizontally on e4 on a size 5 map. Will result in invalid because it's not within bounds vertically.

**Comment by iwle** [comment]
Good catch! I will rectify the inequality comparison bug.

For the second bug, until the put by orientation ability is included in the PutShipCommand, I will leave the default to horizontal boundary checking.

**Comment by iwle** [comment]
Fixed bug. See #112.
