### ISSUE TITLE
App is not exiting properly

### ISSUE THREAD

**Issue by erjillsison** [CS2103-AY1819S2-W14-3/main#141]
After closing the app window, the program does not end properly.
You still have to click the "stop 'MainApp'" button in IntelliJ for the program to completely end.

And the log shows "Process finished with exit code -1" but should be "Process finished with exit code 0"

I've narrowed it down to the following commit that started the issue:
4f80a26b07ffbca521f0cbaf530be7645492bad8

**Comment by iwle** [comment]
The exit bug is caused by the system timer.

**Comment by erjillsison** [comment]
Good catch. Perhaps @bos10 can address this issue

**Comment by bos10** [comment]
Thanks Esther
