### ISSUE TITLE
Restructure command list in UG

### ISSUE THREAD

**Issue by s-tr** [CS2103-AY1819S2-W14-3/main#146]
According to guidelines by the CS2101 tutor, the list of commands must be in alphabetical order of command word. Because of this, I suggest to divide the commands into subsections based on functionality (e.g. ship management, battling).

**Comment by erjillsison** [comment]
Sounds good. How should we go about doing this?

**Comment by iwle** [comment]
As @s-tr said, what we can do is to list it by feature in alphabetical order first, then each of us can commit our UGs to the respective features.

**Comment by iwle** [comment]
See #254, #255.

**Comment by erjillsison** [comment]
Closing this. See #256
