### ISSUE TITLE
Colour code all diagrams

### ISSUE THREAD

**Issue by iwle** [CS2103-AY1819S2-W14-3/main#219]
Colour code all diagrams according to Architecture diagram in Developer Guide. The components are given below:

* Map: red
* Battleship: orange
* Battle: turquoise
* AI: grey
* Statistics: yellow

We have 9 colours: green (UI), navy blue (Logic), purple (Model), grey (AI), yellow (Statistics), pink (Map), orange (Battleship), teal (Commons/Logs), turquoise (Battle), white (Main).

**Comment by bos10** [comment]
I think this is a useful initiative that will help readers understand which diagrams belong to which components.
