### ISSUE TITLE
Allow user to create new battleship types using a Shipyard

### ISSUE THREAD

**Issue by iwle** [CS2103-AY1819S2-W14-3/main#301]
Currently the user is limited to only three types of battleships:

* Destroyer
* Cruiser
* Aircraft carrier

Each of these battleship types have a specific length. In order to improve gameplay and to allow the user to exercise his/her own creativity, the Battleship feature can be extended to a Shipyard feature where a user is given a fixed number of building materials (i.e., cells of length) to create their own battleships. The Battleship types can also be of varying shapes. For example, a battleship can be L-shaped or T-shaped.

This extended feature may be achieved by doing the following by incrementally building upon the existing code in release `v1.4`.

1. Create a generic `UserBattleship` that extends from `Battleship`, in addition to the existing destroyer, cruiser and aircraft carrier classes.
2. Add a method to `Fleet.FleetEntry` to keep track of multiple 'heads` of the battleship object.
3. Add another mode in BattleManager that allows editing.

**Comment by s-tr** [comment]
This will require changing the way the classes are arranged in Battleship from inheritance (`DestroyerBattleship <: Battleship`, each subclass contains information on its shape) to composition (a destroyer battleship is a `Battleship` that contains data on its shape)

**Comment by iwle** [comment]
Keep in view for this feature, not incremental enough.
