### ISSUE TITLE
Coordinates should be considered valid if it follows the format i.e [alphabet][number]

### ISSUE THREAD

**Issue by erjillsison** [CS2103-AY1819S2-W14-3/main#304]
As of now, coordinates with row value beyond 'j' and column value beyond 10 will throw an error.

Because of this, there are inconsistencies on the errors being displayed.
For example, when you have a map size of 8 and try to "shoot a9", the error shown will be coordinates out of bounds. While doing a "shoot a11" command will give an invalid command error.

**Comment by iwle** [comment]
Solution as discussed:

The `isValidCoordinates()` method should take in capitalised letters and should contain a parameter that checks against the `mapGrid.getSize()`. Remove hardcoded regex checks.

- [x] Add `mapSize` parameter to `isValidCoordinates()` method in `Coordinates.java`.
- [x] Remove hardcoded regex checks.

**Comment by iwle** [comment]
Closed. See #334. Thanks.
