### ISSUE TITLE
UG: Command summary not consistent with command format

### ISSUE THREAD

**Issue by erjillsison** [CS2103-AY1819S2-W14-3/main#331]
Our command format is as follow: UPPER_CASE to denote parameters and enclosed in [ ] denotes optional.

The command summary does not follow the proper command formatting.
e.g Attack should be "attack COORDINATES" and "Create a map.." should be "init MAP_SIZE"
![image](https://user-images.githubusercontent.com/22665593/55640382-0b099d80-57fe-11e9-811c-cf8640a74386.png)

**Comment by s-tr** [comment]
Fixed in #393.
