### ISSUE TITLE
PutShipCommand inconsistent error message

### ISSUE THREAD

**Issue by erjillsison** [CS2103-AY1819S2-W14-3/main#339]
The error message displayed when trying to place ships with the coordinates specified being out-of-bounds is inconsistent when the col value =< 10 compared to > 10. 

Would be better and more descriptive if both errors show "Coordinates out-of-bounds" instead.

"The cell index provided is invalid" is shown for put b9
![image](https://user-images.githubusercontent.com/22665593/55712068-a2e6d180-5a20-11e9-9790-704596d24571.png)

While "Coordinates should be of..." error is shown for "put b11"
![image](https://user-images.githubusercontent.com/22665593/55714009-6fa64180-5a24-11e9-8b36-31d4920e73c4.png)

**Comment by iwle** [comment]
FIxed. See #340.
