### ISSUE TITLE
Enemy does not deploy its ships

### ISSUE THREAD

**Issue by s-tr** [CS2103-AY1819S2-W14-3/main#344]
Enemy does not call `Fleet::deployOneBattleship` after placing a battleship. This makes it impossible to use `Fleet::isAllDestroyed` to check for the victory condition.

**Comment by s-tr** [comment]
#345 patches `Enemy` to place its ships via the above method.

@lucydotc Is this okay with you?

**Comment by lucydotc** [comment]
Okay, looks good to me. There was originally no point for the enemy to touch deployed ship.

**Comment by s-tr** [comment]
Will close this issue since it is resolved.
