### ISSUE TITLE
Rename AddressBookParser into BattleshipParser in all diagrams

### ISSUE THREAD

**Issue by bos10** [CS2103-AY1819S2-W14-3/main#376]
Guys we need to rename it, it will affect our diagrams also. I suggest perhaps GameParser? or GameCommandParser?

**Comment by erjillsison** [comment]
It has already been renamed to BattleshipParser. See ab83f89e5d70cb4d1f9d5c68c8c2de39daf538c7. But yes, have to update the diagrams in DG.

**Comment by iwle** [comment]
Good catch. Diagrams have to be updated. All the sequence diagrams refer to :AddressBookParser at the moment.
