### ISSUE TITLE
Edit Model and finalise Component in Developer's Guide

### ISSUE THREAD

**Issue by bos10** [CS2103-AY1819S2-W14-3/main#377]
This portion includes MAP, SHIPS and STATISTICS we need to give a brief description of each component inside the diagram in bullet point below the figure
![image](https://user-images.githubusercontent.com/30528763/56079310-4bcc6c80-5e25-11e9-9a53-0ee3aae00e7d.png)

I will be removing the VersionedAddressBook diagram because it is not used in our application.

**Comment by iwle** [comment]
Thanks for the catch. I will delete the part in the cross. For the part that is circled, I will write a paragraph _above_ the current class diagram to explain its use.
