### ISSUE TITLE
Remove hardcoded boundaries in Coordinates.java

### ISSUE THREAD

**Issue by iwle** [CS2103-AY1819S2-W14-3/main#98]
Boundaries for `Coordinates.java` were hardcoded in v1.1 to simulate the map boundaries. However, since the 2D map is available, it is time to change the `isValidCoordinates()` method in `Coordinates.java` to check using `.mapSize()`.

**Comment by erjillsison** [comment]
It might be better for the PutShipCommand to check for validity regarding the map size so that Coordinates will not be dependent on MapGrid. isValidCoordinates() should just check for formatting instead.

**Comment by iwle** [comment]
I agree. See #97 for more info.

**Comment by iwle** [comment]
The `isValidCoordinates()` stands as it is. It tests the input string against a regex.

Closed. See #100.
